services:
  shared-infrastructure:
    path: ./src/infrastructure/apigateway
    params:
      cfExecutionRole: ${env:CF_EXECUTION_ROLE}
  users:
    path: ./src/modules/user/exports
    params:
      cfExecutionRole: ${env:CF_EXECUTION_ROLE}
